/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // === shadcn/ui CSS variable mappings ===
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // === Lyrical Modernist — DESIGN.md tokens ===
        surface: '#141317',
        'surface-dim': '#141317',
        'surface-bright': '#3a383d',
        'surface-container-lowest': '#0f0e12',
        'surface-container-low': '#1c1b1f',
        'surface-container': '#201f23',
        'surface-container-high': '#2b292e',
        'surface-container-highest': '#353438',
        'on-surface': '#e6e1e7',
        'on-surface-variant': '#cac4d0',
        'inverse-surface': '#e6e1e7',
        'inverse-on-surface': '#313034',
        outline: '#948f9a',
        'outline-variant': '#49454f',
        'surface-tint': '#d0bcff',
        primary: '#e9ddff',
        'on-primary': '#37265e',
        'primary-container': '#d0bcff',
        'on-primary-container': '#594983',
        'inverse-primary': '#665590',
        secondary: '#ccc2dc',
        'on-secondary': '#332d41',
        'secondary-container': '#4a4359',
        'on-secondary-container': '#bab1ca',
        tertiary: '#ffd9e3',
        'on-tertiary': '#492532',
        'tertiary-container': '#efb8c8',
        'on-tertiary-container': '#704654',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#e9ddff',
        'primary-fixed-dim': '#d0bcff',
        'on-primary-fixed': '#210f48',
        'on-primary-fixed-variant': '#4d3d76',
        'secondary-fixed': '#e9def9',
        'secondary-fixed-dim': '#ccc2dc',
        'on-secondary-fixed': '#1e182b',
        'on-secondary-fixed-variant': '#4a4359',
        'tertiary-fixed': '#ffd9e3',
        'tertiary-fixed-dim': '#efb8c8',
        'on-tertiary-fixed': '#31111d',
        'on-tertiary-fixed-variant': '#633b48',
        'surface-variant': '#363438',
         // Backward-compat aliases for shadcn-mapped tokens
         'on-background': '#e6e1e7',
         // shadcn/ui naming conventions (maps to our M3 tokens)
         'primary-foreground': '#37265e',
         'secondary-foreground': '#332d41',
         'destructive-foreground': '#690005',
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        shell: '40px',
        section: '32px',
        card: '24px',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        gutter: '24px',
        base: '4px',
      },
      fontFamily: {
        'display-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'title-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'title-lg': ['22px', { lineHeight: '28px', fontWeight: '500' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '0.15px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.5px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0.25px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
